version: '3'

services:
    db:
        image: postgres:14
        ports:
            - ${POSTGRESQL_PORT}:5432
        container_name: url_shortener_db
        environment:
            POSTGRESQL_USER: ${POSTGRESQL_USER}
            POSTGRESQL_DB:   ${POSTGRESQL_DB}
            POSTGRESQL_PASS: ${POSTGRESQL_PASS}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - ./docker/.data/db:/var/lib/postgresql/data:cached
        env_file:
            - .env
    php:
        build:
            context: 'docker/php8-fpm'
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: url_shortener_php
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ./docker/logs/symfony:/var/www/symfony/var/logs:cached
        environment:
            - SSH_AUTH_SOCK
        env_file:
            - .env
    nginx:
        build: './docker/nginx'
        container_name: url_shortener_nginx
        ports:
            - ${LOCAL_NGINX_PORT}:80
        links:
            - php
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ./docker/logs/nginx/:/var/log/nginx:cached
        env_file:
            - .env